version: "3.8"

services:

  grpc-server:
    build: ./grpc_server
    volumes:
      - ./grpc_server:/app/
    ports:
      - 50051:50051
  
  es:
    build:
      dockerfile: ./es/Dockerfile
      context: ./
    environment:
      discovery.type: single-node
    volumes:
      - ./es/plugin/build/distributions:/distributions
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - grpc-server


